language: c

compiler:
  - gcc

sudo: required

addons:
  apt:
    packages:
      - scons
      - check
      - python

python:
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y check scons
  - scons statsite test_runner

install: pip install pytest==2.3.4 --use-mirrors

script: ./test_runner && py.test integ/
