language: c

compiler:
  - gcc

sudo: false

addons:
  apt:
    packages:
      - scons
      - check
      - python

python:
  - "2.7"

before_install:
  - ls /usr/include | grep check
  - scons statsite test_runner

install: pip install pytest==2.3.4 --use-mirrors

script: ./test_runner && py.test integ/
